// <auto-generated />
using System;
using CarAndAll_ASPReact.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarAndAll_ASPReact.Server.Migrations
{
    [DbContext(typeof(CarAndAllDbContext))]
    partial class CarAndAllDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Abonnement", b =>
                {
                    b.Property<int>("AbonnementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedrijfId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Einddatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AbonnementId");

                    b.HasIndex("BedrijfId");

                    b.ToTable("Abonnementen");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Bedrijf", b =>
                {
                    b.Property<int>("BedrijfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abonnementstype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KvkNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BedrijfId");

                    b.ToTable("Bedrijven");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Klant", b =>
                {
                    b.Property<int>("KlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KlantId");

                    b.ToTable("Klant");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Verhuuraanvraag", b =>
                {
                    b.Property<int>("VerhuuraanvraagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Einddatum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoertuigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZakelijkeHuurderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VerhuuraanvraagId");

                    b.HasIndex("KlantId");

                    b.HasIndex("VoertuigId");

                    b.HasIndex("ZakelijkeHuurderId");

                    b.ToTable("Verhuuraanvragen");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Voertuig", b =>
                {
                    b.Property<int>("VoertuigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VoertuigId");

                    b.ToTable("Voertuigen");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.ZakelijkeBeheerder", b =>
                {
                    b.Property<int>("ZakelijkeBeheerderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedrijfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ZakelijkeBeheerderId");

                    b.HasIndex("BedrijfId")
                        .IsUnique();

                    b.ToTable("ZakelijkeBeheerder");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.ZakelijkeHuurder", b =>
                {
                    b.Property<int>("ZakelijkeHuurderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedrijfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ZakelijkeHuurderId");

                    b.HasIndex("BedrijfId");

                    b.ToTable("ZakelijkeHuurder");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Abonnement", b =>
                {
                    b.HasOne("CarAndAll_ASPReact.Server.Models.Bedrijf", "Bedrijf")
                        .WithMany("Abonnementen")
                        .HasForeignKey("BedrijfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bedrijf");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Verhuuraanvraag", b =>
                {
                    b.HasOne("CarAndAll_ASPReact.Server.Models.Klant", "Klant")
                        .WithMany("Verhuuraanvragen")
                        .HasForeignKey("KlantId");

                    b.HasOne("CarAndAll_ASPReact.Server.Models.Voertuig", "Voertuig")
                        .WithMany("Verhuuraanvragen")
                        .HasForeignKey("VoertuigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarAndAll_ASPReact.Server.Models.ZakelijkeHuurder", "ZakelijkeHuurder")
                        .WithMany("Verhuuraanvragen")
                        .HasForeignKey("ZakelijkeHuurderId");

                    b.Navigation("Klant");

                    b.Navigation("Voertuig");

                    b.Navigation("ZakelijkeHuurder");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.ZakelijkeBeheerder", b =>
                {
                    b.HasOne("CarAndAll_ASPReact.Server.Models.Bedrijf", "Bedrijf")
                        .WithOne("ZakelijkeBeheerder")
                        .HasForeignKey("CarAndAll_ASPReact.Server.Models.ZakelijkeBeheerder", "BedrijfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bedrijf");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.ZakelijkeHuurder", b =>
                {
                    b.HasOne("CarAndAll_ASPReact.Server.Models.Bedrijf", "Bedrijf")
                        .WithMany("ZakelijkeHuurders")
                        .HasForeignKey("BedrijfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bedrijf");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Bedrijf", b =>
                {
                    b.Navigation("Abonnementen");

                    b.Navigation("ZakelijkeBeheerder")
                        .IsRequired();

                    b.Navigation("ZakelijkeHuurders");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Klant", b =>
                {
                    b.Navigation("Verhuuraanvragen");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.Voertuig", b =>
                {
                    b.Navigation("Verhuuraanvragen");
                });

            modelBuilder.Entity("CarAndAll_ASPReact.Server.Models.ZakelijkeHuurder", b =>
                {
                    b.Navigation("Verhuuraanvragen");
                });
#pragma warning restore 612, 618
        }
    }
}
